### PR TITLE
Merge develop from google/blockly.

### PR DESCRIPTION
**Pull request by rachel-fenichel**
Integrates the all-purpose horizontal toolbox code.

### CODE REVIEW

**Comment by rachel-fenichel** [comment]
#345

**Comment by tmickel** [comment]
looks great to me, thanks again Rachel!

**Comment by tmickel** [comment]
P.S.:

I believe this also fixes #53 and #222 - can you confirm?

Does it also fix #62?

**Comment by rachel-fenichel** [comment]
Yes, I think it fixes all of those.  Will mark.

**Pull request merged**
