### PR TITLE
Fix typo and duplicate line of code

### PR DESCRIPTION
**Pull request by fsih**

### CODE REVIEW

**Comment by rachel-fenichel** [comment]
LGTM.  I can't tell if this exists upstream (could be a merge artifact) but we should check.

**Review by paulkaplan — APPROVED** [review]

**Comment by picklesrus** [comment]
@rachel-fenichel Duplicate code isn't in upstream (though the thw typo is).

**Comment by paulkaplan** [comment]
@fsih reminder to merge your PRs once they are LG'd!

**Comment by fsih** [comment]
Oooops thanks!

**Pull request merged**
