### PR TITLE
Add New Horizontal Block Assets And Add Missing Categories

### PR DESCRIPTION
**Pull request by TheBrokenRail**
Categories:
- [x] Motion
- [x] Looks
- [x] Give Category Icons Colors

### CODE REVIEW

**Comment by TheBrokenRail** [comment]
Comments?

**Comment by TheBrokenRail** [comment]
I believe I've added all the things that are missing from horizontal blocks.

**Review by thisandagain — CHANGES_REQUESTED** [review]
@TheBrokenRail Thanks. The build is failing due to lint errors. Please make sure all tests are passing before submitting for review: https://travis-ci.org/LLK/scratch-blocks/jobs/187733760

**Comment by TheBrokenRail** [comment]
Fixed!

**Comment by TheBrokenRail** [comment]
Since it now passes the tests could you approve the "changes requested"?

**Comment by TheBrokenRail** [comment]
@thisandagain Any comments?

**Comment by TheBrokenRail** [comment]
Fixed the "alt" values

**Comment by TheBrokenRail** [comment]
Should I remove horizontal only blocks or keep them?

**Comment by TheBrokenRail** [comment]
@thisandagain And by "horizontal only blocks" I mean, up, down, back, reset size, home, and shrink

**Comment by thisandagain** [comment]
We are focused on the vertical grammar between now and the alpha. If you'd like to explore the horizontal grammar I suggest you create a personal fork of the `scratch-gui`.

**Pull request closed without merging**
