### PR TITLE
Apply small fixes in block_drag_surface.js

### PR DESCRIPTION
**Pull request by rachel-fenichel**
### Resolves

Cleaning up for merges.

### Proposed Changes

Small changes: making annotations more accurate (work I've been doing in blockly to decrease the number of build warnings); mark some code that is specific to scratch blocks; tweak some code that lint cleanup changed in blockly.

### Reason for Changes
Cleaning up for merges.

### Test Coverage

No functional changes.

### CODE REVIEW

**Review by paulkaplan — APPROVED** [review]
LG

**Comment by thisandagain** [comment]
@rachel-fenichel Looks good, but tests appear to be failing.

**Comment by rachel-fenichel** [comment]
Tests are failing because I'm using four space indent and eslint wants two (sigh).  


Does anyone object if I turn the indent rule to `warn` while I do this stuff, and turn it back to `error` when I get us up to a merge and/or next version of eslint?

**Comment by thisandagain** [comment]
@rachel-fenichel No objections here.

**Pull request merged**
