### PR TITLE
Changing color of list blocks 

### LINKED ISSUE #1257: List blocks should be a different color from variable blocks.
### Expected Behavior

List blocks and variable blocks should be different colors because lists and variables are able to share names. See discussion in #1245 for more info.

### Actual Behavior

Currently, list blocks and variable blocks are the same color.

### Steps to Reproduce

Create a new variable.
Create a new list.

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

### PR DESCRIPTION
**Pull request by kchadha**
Changing color of list blocks to differentiate from variable blocks.

### Resolves

Resolves #1257 

### Proposed Changes

Change the color of list blocks to differentiate from scalar variables according to color chart in #600 and discussion in #1257.

### Reason for Changes

Lists and variables will be able to share names, so color is a visible way of differentiating between the blocks that would otherwise look the same (e.g. variable getter).

### Test Coverage

Existing tests pass.

### CODE REVIEW

**Review by rachel-fenichel — APPROVED** [review]

**Comment by mrjacobbloom** [comment]
Note that the data-category attribute for list blocks is the same despite a color difference, that should probably change or else list blocks will only be theme-able in the same color as scalar blocks

**Comment by kchadha** [comment]
@mrjacobbloom I'm not sure what you mean by "theme-able"...

**Comment by mrjacobbloom** [comment]
The SVG <g> element for each block has an attribute data-category that reflects the category property in the object passed to jsonInit so that blocks can be styled by category with plain old CSS. Right now both scalar and list blocks are using the category `Blockly.Categories.data` but we should probably add a lists category to differentiate now that they're different colors. I can do that in a separate PR though.

**Comment by kchadha** [comment]
Ah, okay. If you're okay with taking that on, I will merge this PR.

**Pull request merged**
