### PR TITLE
Make Broadcast shadow blocks more consistent.

### PR DESCRIPTION
**Pull request by TheBrokenRail**
This goes with LLK/scratch-vm#368 to update the spec map.

### CODE REVIEW

**Comment by tmickel** [comment]
@TheBrokenRail:

Does this actually work as intended? As far as I remember, the "when broadcast" hat as implemented does not evaluate reporters which are dropped into it.

**Comment by TheBrokenRail** [comment]
Fixed!

**Comment by TheBrokenRail** [comment]
I used the "check" value with a value of "Broadcast" as well as the output of the shadow "Broadcast" this makes sure nothing else is allowed (no reporters)

**Comment by TheBrokenRail** [comment]
Any comments (I fixed the reporter issue), if not is this ready to merge along with the VM PR?

**Comment by thisandagain** [comment]
We will cover this in a separate pass where we address drop-down menus.

**Pull request closed without merging**
