### PR TITLE
Use variables to set block colors

### LINKED ISSUE #802: Use variables to define colors in default xml
This would make it easier to change categories colors with out have to change it in two places.
# Current
```"colour='#000000'"```
# Proposed
```"colour='" + Blockly.Colours.thing.colour + "'```

### PR DESCRIPTION
**Pull request by Tymewalk**
### Resolves

Resolves #802 - [direct link](https://github.com/LLK/scratch-blocks/issues/802)

### Proposed Changes

Replaces the colors in `blocks_vertical/default_playground.js` with `Blockly.Colours` variables.

### Reason for Changes

Block colors can now easily be set through `core/colours.js`, rather than having to change both files individually to fully update it.

### Test Coverage

Changing the colors in `core/colours.js`, then recompiling changes the colors in the default playground..

### Additional Notes

I found various different coding styles throughout the repo, and could not find a specific style guide. If a different style is being used than what I have here, please let me know and I will fix it.

### CODE REVIEW

**Comment by Tymewalk** [comment]
It looks like the checks failed because the lines were too long. I'll fix that now.

**Comment by Tymewalk** [comment]
Hm, using variables doesn't seem to work, the names would still be too long. I'll have to simply break the line into multiple parts.

**Comment by Tymewalk** [comment]
This has been fixed in the most recent commit. `npm test` exits without any errors.

**Comment by rschamp** [comment]
Thanks @Tymewalk, but closing for the reasons outlined in #802.

**Pull request closed without merging**
