### PR TITLE
Properly center text in fields based on calculated width

### PR DESCRIPTION
**Pull request by tmickel**
Before:
screen shot 2016-06-13 at 8 04 42 pm

After:
screen shot 2016-06-13 at 8 04 53 pm

### CODE REVIEW

**Comment by tmickel** [comment]
Hmm, need to fix a case for RTL:
screen shot 2016-06-13 at 8 09 07 pm

**Comment by rachel-fenichel** [comment]
Just looking at the screenshots, you might need an extra space before "and wait"--that is, after the dropdown field, if there's a label following.

**Comment by tmickel** [comment]
yep - not sure what's going on with that...

**Comment by rachel-fenichel** [comment]
lgtm for ltr

**Comment by tmickel** [comment]
I've pushed an RTL fix, but I have no idea how it works either :) Arrived at it by flipping around subtractions and minus signs. `text-anchor` causes some weird stuff to happen in RTL...

May try to investigate why this works in the morning.

**Pull request merged**
