### PR TITLE
Add classes for insertion-markers and replacement-rings

### PR DESCRIPTION
**Pull request by mrjacobbloom**
If a block is an insertion-marker, it'll have the class `blocklyInsertionMarker`. If a reporter, input, or inputShape has the replacementGlowFilter, it'll also have the class `blocklyReplaceable`.

### CODE REVIEW

**Comment by tmickel** [comment]
Just wondering, why are you using the class here (all your others are using the data attribute)?

**Comment by mrjacobbloom** [comment]
I guess because category and shape are general information that you'd expect to find on any block, but replacement/insertion are more like special cases that only happen one-at-a-time. It could just as easily be an attribute though

**Comment by mrjacobbloom** [comment]
The main reason I started using data attributes is because the list of shapes could be several long and I didn't want to worry about how to remove unwanted shapes if a block's shape changed without affecting other classes already on the block. That's not an issue in these cases

**Comment by tmickel** [comment]
Ok, makes sense to me!

**Pull request merged**
