### PR TITLE
Remove `maxBlocks` (fix #309)

### LINKED ISSUE #309: Remove `maxBlocks` feature
Demo has been removed as per #304 but the feature itself should be removed.

### PR DESCRIPTION
**Pull request by tmickel**
Resolves #309

### CODE REVIEW

**Comment by RoboErikG** [comment]
This is an example of something you might want to support for other devs. Blockly Games uses this for guided lessons like level 4 of the Maze: https://blockly-games.appspot.com/maze?lang=en&level=4&skin=0

**Comment by tmickel** [comment]
@thisandagain thoughts?

**Comment by thisandagain** [comment]
`maxBlocks` runs counter to some of our [design and pedagogical sensibilities](https://scratch.mit.edu/developers) in that it's primary use case is to limit the number of viable options for solving a problem (e.g. Code.org or your example from Blockly Games). While we understand the reasoning for this type of approach, we disagree with this emphasis on "correctness" and instead prefer to put emphasis on providing the user with many pathways and creative possibilities for how they may go about a given task.

**Comment by RoboErikG** [comment]
So it sounds like you want to discourage other devs from using that approach, correct?

**Comment by tmickel** [comment]
At least we aren't going to maintain code that specifically is for that approach, I think.

**Pull request merged**
