### PR TITLE
Vertical category menu

### PR DESCRIPTION
**Pull request by ericrosenbaum**
### Resolves

Closes https://github.com/LLK/scratch-blocks/issues/1039

### Proposed Changes

Switch to a vertical layout for the blocks category menu. We replaced the stacked category layout because we do not plan on supporting it any more.

One area we got tripped up on is how to specify the different widths involved. We took out the line that had the flyouts inherit their width from the toolbox, instead always having them use their `DEFAULT_WIDTH`. @rachel-fenichel do you have any thoughts about the way this was done?

### CODE REVIEW

**Comment by rachel-fenichel** [comment]
Since this is a decently large in functionality (though not in code), here are the standard questions:

- [x] Does the horizontal toolbox work?
- [x] Does the simple horizontal flyout work?
- [x] Does the vertical toolbox work?
- [x] Does the simple vertical flyout work?
- [x] Are the delete areas correct?
- [x] Does it work when you zoom far in?
- [x] Does it work when you zoom far out?

Have you tested 

- [x] In LTR mode
- [x] In RTL mode
- [x] In the multi-playground
- [x] On Android
- [x] On iOS
- [x] In Safari
- [x] In Edge
- [x] In IE11
- [x] In Firefox
- [x] In Chrome

**Comment by TheBrokenRail** [comment]
Will there be an option to use the "classic" scratch toolbox?

**Comment by ericrosenbaum** [comment]
Thanks for keeping us on our toes @rachel-fenichel. The current state on the develop branch of our horizontal toolbox is pretty broken, as are all the top and bottom layouts for vertical and horizontal, and this PR doesn't change that. Delete areas, zooming, and RTL are working fine and not broken by the PR. AFAIK we're not doing full cross-browser testing until after our alpha release, but chrome, safari and firefox look fine.

**Comment by rachel-fenichel** [comment]
@ericrosenbaum the horizontal toolbox is currently in use (cozmo) so at least one horizontal toolbox configuration currently works.  I'm worried about breaking that.

Not doing full cross-browser testing: I don't want to wait until December to find out that a change in August broke touch on iOS, because then there's a lot more work to fix it.  Please do a cursory test on iOS, Android, IE11, and Edge.  

If it's broken it doesn't need to block this PR, but you should file a bug so we know that this change broke it.

What about the simple vertical toolbox?  (Flyout only.)

**Comment by ericrosenbaum** [comment]
Sounds good, we're doing some of that testing now. 

A question from @paulkaplan  that came up when testing touch devices: because of `Blockly.bindEvent` (which calls `preventDefault` on the event) on the categories, one cannot scroll a long category list. Do you know any way of getting around that?

Aside from that things are looking fine. We noticed a bunch of layout bugs in Edge and IE11, but those are unrelated to this PR and I will file them separately.

**Comment by paulkaplan** [comment]
Added a commit to allow a horizontal layout of the category menu also.

image

**Comment by ericrosenbaum** [comment]
@TheBrokenRail sorry, we don't currently plan to keep supporting the "classic" toolbox style.

**Comment by msintov** [comment]
@ericrosenbaum If I set the flyout to autoclose in flyout_vertical.js, I find that once a block is dragged out and the flyout autocloses, the area where the flyout used to be is still an active delete area. Also, the workspace is only to the right of the flyout would be, whether the flyout is opened or closed. Is this behavior unintentional? Thanks in advance.

**Comment by ericrosenbaum** [comment]
Sorry @msintov- that's unintentional! We neglected to test with autoclose. Sounds like we'll need to fix the workspace positioning and the delete area. Would you please submit an issue? Thanks!

**Comment by msintov** [comment]
@ericrosenbaum Thanks for the note. Logged it here: https://github.com/LLK/scratch-blocks/issues/1067

**Pull request merged**
