### PR TITLE
Fixed blocks dragging under toolbox

### LINKED ISSUE #814: Blocks being dragged appear under the blocks categories
### Expected Behavior

Blocks being dragged should remain above the blocks block category menu when they are dragged into that space.

### Actual Behavior

blocks-under-categories mov

### Steps to Reproduce

1. Start Dragging a block
2. Drag the block into the block category menu

### Operating System and Browser

OS: macOS 10.12.1
Browser: Chrome Version 56.0.2924.87 (64-bit)

### PR DESCRIPTION
**Pull request by lifeinchords**
Closes #814 

drag-blocks-fix--814 mov

with @paulkaplan

### CODE REVIEW

**Comment by rachel-fenichel** [comment]
lgtm

**Review by rschamp — APPROVED** [review]
Looks good!

**Comment by picklesrus** [comment]
Just an FYI that this probably happened when scratch-blocks updated from upstream since blockly's behavior is the opposite.  This is something to watch out for next time the merge happens and perhaps a reason to setup rerere so it merges this change automagically in the future (This assumes I understand how rerere works. Git is still a mystery to me sometimes)

**Comment by lifeinchords** [comment]
Thanks for your feedback @picklesrus! git rerere sounds pretty cool -- I'll chat with folks here to learn how we can use it to keep changes like this going, as the upstream changes.

**Pull request merged**
