### PR TITLE
Add back variables

### PR DESCRIPTION
**Pull request by paulkaplan**
Adds back the data category with variable blocks and restyles the button for adding variables.

The "new variable" creation prompt will be handled through the GUI, so it isn't part of this.

screen shot 2017-04-20 at 1 37 32 pm

### CODE REVIEW

**Comment by towerofnix** [comment]
Note the button label in 2.0 is "Make a Variable", not "Create variable...", and that the 3.0 design also goes with "Make a Variable" – see @carljbowman's post [here](https://github.com/LLK/scratch-blocks/issues/535#issuecomment-280391920) and this design image:

"Make a Variable" button

That said, the required change would be in the `en.json` translation file (`NEW_VARIABLE`).

**Comment by paulkaplan** [comment]
@liam4 yup I noticed that but was going to change it separately. @rachel-fenichel there are a few places where `NEW_VARIABLE` is defined, do I just change all of them?

**Comment by rachel-fenichel** [comment]
To avoid merge conflicts, and since you're going to have separate buttons for data and lists, you should 
- add a new entry in msg/messages.js (such as Blockly.Msg.NEW_DATA)
- use that message in place of NEW_VARIABLE
- run build.py

msg/messages.js is used to build some files with all of our messages in a format that translatewiki can parse.
The .json files for various languages come from translatewiki and have everything they've translated for a given language.  The .js files for languages are built based on the .json files, falling back to english if a translation is lacking.

**Review by rschamp — APPROVED** [review]
@paulkaplan This looks great, thanks.  I think you can merge without considering that text for now, since we're going to be addressing localization soon anyway.

**Pull request merged**
